module.exports = [
  {
    name: 'background/Background',
    count: 11,
    offset: {x: 0, y: 0},
    attrNames:['Cyan','Peach','Yellow','Green','Blue','Violet','Pink','Purple','Caramel','Gray','Beige'],
    required: true,
  },
  {
    name: 'fur/Fur',
    count: 9,
    offset: {x:  -1080, y: 0},
    attrNames:['Fawn','Orange','Red','Pink','Chocolate','Gray','Maroon','Gold','Snow White'],
    required: true,
  },
  {
    name: 'face/Face',
    count: 7,
    offset: {x: -1080, y: 0},
    attrNames:['Blue Eyes','Sharingan','Tobacco','$PUBE Beard','Beard','Red Laser Eyes','Blue Laser Eyes'],
    required: true,
  },
  {
    name: 'nose/Nose',
    count: 7,
    offset: {x: -1080, y: 0},
    attrNames:['Black','Dark Brown','Light Brown','Flesh','Pink','Hoop Gold Piercing','Stud Gold Piercing'],
    required: true,
  },
  {
    name: 'earaccessory/Earaccessory',
    count: 9,
    offset: {x: -1080, y: 0},
    attrNames:['','Stud Gold Piercing','Hoop Gold Earring','Stud Silver Piercing','Hoop Silver Earring','Double Stud Gold Piercing','Triple Stud Gold Piercing',
    'Double Stud Silver Piercing','Triple Stud Silver Piercing'],
    required: false,
  },
  {
    name: 'eyewear/Eyewear',
    count: 21,
    offset: {x: -1080, y: 0},
    attrNames:['','Yellow Rounded Shades','Cyan Rounded Shades','Black Rectangular Shades','Blue Rectangular Shades','Yellow Cat-Eye Shades','Clear Cat-Eye Shades',
    'Blue-Green Goggles','Pink Goggles','Blue Heart Shades','Purple Heart Shades','3D Glasses','Sports Sunglasses','Blue Cyclops','Red Cyclops','Black Aviator Shades',
    'Reading Eyeglasses','Eye Patch','Golden Aviator Shades','Bitcoin Shades','Hi-Tech Spectacle'],
    required: false,
  },
  {
    name: 'headwear/Headwear',
    count: 49,
    offset: {x: -1080, y: 0},
    attrNames:['','CryptoCobain Hat','Brown Short Hair','Floral Unicorn Horn','Johnny Bravo Hair','Wonder Woman Crown','Blue Beanie','Red Beanie','Beret','Green Visor','blue Visor','Hardhat','Party Hat','Bull Horn',
    'Cupcake','Red Apple','Green Apple','Trench Helmet','Mohawk Hair','Spike Hair','Emo Hair','Alpine Hat','Slouch Hat','Ashigaru Hat','Trapper Hat','Newsboy Hat','Propeller Hat',
    'Miner Helmet','Turban','Sakkat Hat','Flat Cap','Afro Hair','Nerdy Hair','Painter Hat','Reindeer Headband','Melted Ice Cream','Commie Hat','Fez','Bowler Hat','Bangs','Unicorn',
    'Fedora Hat','Brown Brush Up Hair','Bitcoin Cap','Fox Mask','Bear Onesie','Pressure Suit Helmet','Fire Dragon','Charizard'],
    required: false,
  },
  {
    name: 'outfit/Outfit',
    count: 98,
    offset: {x: -1080, y: 0},
    attrNames:['','Bear Onesie','Black Jacket w/ Fur','Pressure Suit','Hoodie Seal w/ Print','Mafia Suit','Samurai w/ Sword','Armed Forces','Denim w/ Owl Tattoo','Fire Dragon',
      '$PUBE Jacket','Pressure Suit w/o Helmet','Iron Man Suit','Charizard','Wonder Woman','Mummy Tape','Bathrobe w/ Golden Lace','Tie Dye Shirt','Party Suit','Adventurer Jacket','Caramel Padded Armor','Spiked Collar','K9 Vest',
      'T-shirt w/ Headphone','Jeweler','Blue Camouflage w/ Silver Dog Tag','Purple Stripes w/ Black Dog Tag','Fang Necklace','Black Approving Corgi Shirts','Pink Hockey Jersey',
      'Blue Hockey Jersey','Yellow Football Jersey','White Football Jersey','School Uniform','Polkadots Shirt','Stripes Long Sleeves','Maroon Scarf','Pink T-shirt w/ Paw Print',
      'Red Sweater','Navy Blue Necktie','Maroon Necktie','Blue Jumper','Purple Jumper','Brown Cross-Stitch Shirt','Green Cross-Stitch Shirt','Aegean Hoodie','Nude Hoodie',
      'White Sleeveless Shirt','Blue Sleeveless Shirt','Yellow Hawaiian Shirt','White Hawaiian Shirt','Brown Trench Coat','Spruce Blazer Suit','Black Blazer Suit','Navy Blue Bow Tie',
      'Red Bow Tie','Blue Shirt','Vest','Peach Cardigan','Sky Blue Jacket','Life Vest','Red Checkered Scarf','Green Checkered Scarf','Yellow Varsity Jacket','Pink Varsity Jacket',
      'Green Padded Armor','Yellow V-neck w/ Bone Print','Pink V-neck w/ Bone Print','Heather Padded Vest','Sky Blue Padded Vest','Red Polkadot Tie','Blue Polkadot Tie','Nude Striped Tie',
      'Violet Striped Tie','Xray Shirt','White T-shirt w/ Rainbow Print','Yellow T-shirt w/ Rainbow Print','Scientist Suit','White Ethereum Shirt','Black Ethereum Shirt',
      'White Shirt w/ Silver Chain','Black Shirt w/ Silver Chain','Camouflage w/ Silver Dog Tag','Black Shirt Stripe w/ Dog Tag','Hawaiian Lei','Gold Collar','Bitcoin Jacket',
      'Rainbow Suspender w/ Bowtie','Denim Vest','Gray Round Neck Shirt','Royal Cape','Fur Jacket','Overlord Cape','Vintage Suit','Black Round Neck Shirt','Jaguar Shirt','Cyan Scarf',''],
    required: false,
  },
]