module.exports = [
  {
    name: 'background/background',
    count: 2,
    offset: {x: 0, y: 0},
    attrNames:['Grey','Beige'],
    required: true,
  },
  {
    name: 'fur/fur',
    count: 1,
    offset: {x:  -4500, y: 0},
    attrNames:['Grey'],
    required: true,
  },
  {
    name: 'face/Face',
    count: 1,
    offset: {x: -4500, y: 0},
    attrNames:['PUBE Beard'],
    required: true,
  },
  {
    name: 'nose/nose',
    count: 1,
    offset: {x: -4500, y: 0},
    attrNames:['pink'],
    required: true,
  },
  {
    name: 'earaccessory/earaccessory',
    count: 2,
    offset: {x: -4500, y: 0},
    attrNames:['','Double Stud Silver Piercing'],
    required: false,
  },
  {
    name: 'outfit/outfit',
    count: 5,
    offset: {x: -4500, y: 0},
    attrNames:['','Rainbow Suspender Bowtie',
    'Pube Jacket','Denim + Owl Tattoo','Cobie'],
    required: false,
  },
  {
    name: 'eyewear/eyewear',
    count: 3,
    offset: {x: -4500, y: 0},
    attrNames:['','3D Glasses','Eye Patch'],
    required: false,
  },
  {
    name: 'headwear/headwear',
    count: 4,
    offset: {x: -4500, y: 0},
    attrNames:['','Miner Hat Yellow','Miner Hat Orange','Reindeer Hat'],
    required: false,
  },
]