module.exports = [
  {
    name: 'background/background',
    count: 11,
    offset: {x: 0, y: 0},
    attrNames:['Cyan','Peach','Yellow','Green','Blue','Violet','Pink','Purple','Caramel','Grey','Beige'],
    required: true,
  },
  {
    name: 'fur/fur',
    count: 8,
    offset: {x:  -4500, y: 0},
    attrNames:['Fawn','Orange','Red','Snow White','Pink','Chocolate','Maroon','Grey'],
    required: true,
  },
  {
    name: 'face/face',
    count: 6,
    offset: {x: -4500, y: 0},
    attrNames:['Smiling','Happy','Crazy','Disapproving','Thick Eyebrows','Cigarette'],
    required: true,
  },
  {
    name: 'nose/nose',
    count: 5,
    offset: {x: -4500, y: 0},
    attrNames:['black','dark brown','light brown','flesh','pink'],
    required: true,
  },
  {
    name: 'eyewear/eyewear',
    count: 4,
    offset: {x: -4500, y: 0},
    attrNames:['','Goggles 1','Goggles 2','Eye Patch'],
    required: false,
  },
  {
    name: 'headwear/headwear',
    count: 9,
    offset: {x: -4500, y: 0},
    attrNames:['','Graduation Cap','Chef Hat','Pirate Hat 1','Pirate Hat 2','Bandana 1','Bandana 2','Taekwondo','Demon'],
    required: false,
  },
  {
    name: 'earaccessory/earaccessory',
    count: 4,
    offset: {x: -4500, y: 0},
    attrNames:['','Hoop Gold Piercing','Stud Silver Piercing','Double Stud Silver Piercing'],
    required: false,
  },
  {
    name: 'outfit/outfit',
    count: 65,
    offset: {x: -4500, y: 0},
    attrNames:['','Baseball 1','Baseball 2','Football Jersey 1','Football Jersey 2','Graduation Gown','Chef','Pirate Red','Pirate Blue',
    'Bandana Red','Bandana Purple','Taekwondo','King Crown Black','King Crown Red','Equestrian','Soldier','Basketball 1','Basketball 2',
    'Hockey 1','Hockey 2','School Uniform','Polkadots 1','Polkadots 2','Stripe Longsleeves 1','Stripe Longsleeves 1','Stripe Longsleeves 2','Scarf Black',
    'Scarf Maroon','Paw Print Pink','Paw Print Yellow','Sweater Red','Sweater Purple','Jumper Blue','Jumper Purple','Cross Stitch 1',
    'Cross Stitch 2','Mummy','Hoody 1','Hoody 2','Bow Tie Blue','Bow Tie Red','Life Vest','Gold Collar','Padded Armor Green','Padded Armor Brown',
    'V-neck + Bone Print 1','V-neck + Bone Print 2','Padded Vest 1','Padded Vest 2','Polkadot Tie 1','Polkadot Tie 2','Striped Tie 1','Striped Tie 2',
    'Spiked Collar','Xray Shirt','Tshirt + Rainbow 1','Tshirt + Rainbow 2','Tshirt + Etherium 1','Tshirt + Etherium 2','Tshirt Camouflag + Dog Tag Silver 1',
    'Tshirt Camouflag + Dog Tag Silver 2','Stripe tshirt + Dog Tag Black 1','Stripe tshirt + Dog Tag Black 2','Fang Necklace','Rainbow Suspender Bowtie'],
    required: false,
  },
]