module.exports = [
  {
    name: 'background/background',
    count: 11,
    offset: {x: 0, y: 0},
    attrNames:['Cyan','Peach','Yellow','Green','Blue','Violet','Pink','Purple','Caramel','Grey','Beige'],
    required: true,
  },
  {
    name: 'fur/fur',
    count: 8,
    offset: {x:  -4500, y: 0},
    attrNames:['Fawn','Orange','Red','Snow White','Pink','Chocolate','Maroon','Grey'],
    required: true,
  },
  {
    name: 'face/Face',
    count: 10,
    offset: {x: -4500, y: 0},
    attrNames:['Smiling','Happy','Laughing','Whistling','Crazy','Hungry','Raised Eyebrow','Disapproving','Eyelashes','PUBE Beard'],
    required: true,
  },
  {
    name: 'nose/nose',
    count: 5,
    offset: {x: -4500, y: 0},
    attrNames:['black','dark brown','light brown','flesh','pink'],
    required: true,
  },
  {
    name: 'earaccessory/earaccessory',
    count: 4,
    offset: {x: -4500, y: 0},
    attrNames:['','Hoop Gold Piercing','Stud Silver Piercing','Double Stud Silver Piercing'],
    required: false,
  },
  {
    name: 'outfit/outfit',
    count: 80,
    offset: {x: -4500, y: 0},
    attrNames:['','Baseball 1','Baseball 2','','Football Jersey 1','Football Jersey 2','Graduation Gown','Chef','Pirate Red','Pirate Blue',
    'Bandana Red','Bandana Purple','Taekwondo','King Crown Black','King Crown Red','Wizard','Santa Clause','Equestrian','Samurai','Super Mario',
    'Luigi','Basketball White','Basketball Yellow','Hockey 1','Hockey 2','School Uniform','Polkadots 1','Polkadots 2','Stripe Longsleeves 1',
    'Stripe Longsleeves 2','Scarf Black','Scarf Maroon','Paw Print Pink','Paw Print Yellow','Sweater Red','Sweater Purple',
    'Jumper Blue','Jumper Purple','Cross Stitch 1','Cross Stitch 2','Mummy','Hoody 1','Hoody 2','Bathrobe','BLazer','Cone of Shame','Bow Tie Blue','Bow Tie Red',
    'Royal Cape','Life Vest','Hazmat Suit','Gold Collar','Adventurer Jacket','Varsity Jaket 1','Varsity Jaket 2',
    'Padded Armor Green','Padded Armor Brown','V-neck + Bone Print 1','V-neck + Bone Print 2',
    'Padded Vest 1','Padded Vest 2','Polkadot Tie 1','Polkadot Tie 2','Striped Tie 1','Striped Tie 2',
    'Spiked Collar','Xray Shirt','Tshirt + Rainbow 1','Tshirt + Rainbow 2','Tshirt + Etherium 1','Tshirt + Etherium 2','K9 Vest','Tshirt Camouflage + Dog Tag Silver 1',
    'Tshirt Camouflage + Dog Tag Silver 2','Stripe tshirt + Dog Tag Black 1','Stripe tshirt + Dog Tag Black 2','Fang Necklace','Rainbow Suspender Bowtie',
    'Pube Jacket','Denim + Owl Tattoo','Cobie'],
    required: false,
  },
  {
    name: 'eyewear/eyewear',
    count: 14,
    offset: {x: -4500, y: 0},
    attrNames:['','Round Shades 1','Round Shades 2','Cat Eye Shades 1','Cat Eye Shades 2','Rectangle Shades 1','Rectangle Shades 2','Goggles 1','Goggles 2',
      'Monocle','Cyclops Red','Cyclops Blue','3D Glasses','Eye Patch'],
    required: false,
  },
  {
    name: 'headwear/headwear',
    count: 9,
    offset: {x: -4500, y: 0},
    attrNames:['','Baseball Cap','Graduation Hat','Chef Hat','Pirate Hat 1','Pirate Hat 2','Bandana 1','Bandana 2','Taekwondo Headband','Demon','Basketball Headband',
      'Beret','Party Hat','Cupcake','Mohawk Green','Mohawk Orange','Trapper Hat Brown','Newsboy Hat 1','Newsboy Hat 2','Miner Hat Yellow','Miner Hat Orange','Reindeer Hat'],
    required: false,
  },
]